Par and request object only
oauthstuff/draft-oauth-par pull request #46
Opened 2020-05-10 14:21 UTC by tlodderstedt

I added text to support PAR and request object only functionalities. 

Note: I added another server metadata parameter "require_request_objects" to allow the AS to indicate it generally requires request objects.

2020-05-10 17:36 UTC, panva commented
> If the client uses dynamic client registration, setting the metadata parameter `request_object_signing_alg` MUST cause the authorization server to accept request objects for that particular client at the pushed authorization request endpoint only.

I don’t particularly agree with this. That option, as will be made clear by oidc errata has a meaning that shouldn’t be made different if the server supports par or not.

2020-05-10 17:47 UTC, tlodderstedt commented
please propose text - the current text intentionally focuses on PAR but does not prescribe any behavior at another endpoint

2020-05-10 18:31 UTC, panva commented
@tlodderstedt i believe you've made a typo in the PR when it comes that particular paragraph i quoted. I'll push to the same branch in a bit.

2020-05-10 18:54 UTC, panva commented
@tlodderstedt i see the intent but the metadata `require_request_objects` being only applied to PAR or in general defining new metadata that is named generically but only applied to PAR just doesn't make sense to me.

Here's what i imagine the effects of each client/as metadata in isolation should be, WDYT? If you agree i can propose changes.

<img width="1563" alt="Screenshot 2020-05-10 20 52 09" src="https://user-images.githubusercontent.com/241506/81507821-221f9680-9300-11ea-976a-366c1ab13db6.png">

<details>
<summary>Source markdown</summary>

```

| AS require_pushed_authorization_requests | AS require_request_objects | client request_object_signing_alg | client require_pushed_authorization_requests | Regular Authorization Request | Require Request Object | PAR |
|-|-|-|-|-|-|-|
| false | false | undefined | false | MAY | MAY (any alg) | MAY |
| **true** | false | undefined | false | **FORBIDDEN** | MAY (any alg) | **MUST** |
| false | **true** | undefined | false | MAY | **MUST** (any alg) | MAY |
| false | false | e.g. **PS256** | false | MAY | **MUST** (PS256) | MAY |
| false | false | undefined | **true** | **FORBIDDEN** | MAY (any alg) | **MUST** |

```
</details>

2020-05-10 18:56 UTC, panva requested changes
@tlodderstedt i see the intent but the metadata `require_request_objects` being only applied to PAR or in general defining new metadata that is named generically but only applied to PAR just doesn't make sense to me.

Here's what i imagine the effects of each client/as metadata in isolation should be, WDYT? If you agree i can propose changes.

<img width="1563" alt="Screenshot 2020-05-10 20 52 09" src="https://user-images.githubusercontent.com/241506/81507821-221f9680-9300-11ea-976a-366c1ab13db6.png">

<details>
<summary>Source markdown</summary>

```

| AS require_pushed_authorization_requests | AS require_request_objects | client request_object_signing_alg | client require_pushed_authorization_requests | Regular Authorization Request | Require Request Object | PAR |
|-|-|-|-|-|-|-|
| false | false | undefined | false | MAY | MAY (any alg) | MAY |
| **true** | false | undefined | false | **FORBIDDEN** | MAY (any alg) | **MUST** |
| false | **true** | undefined | false | MAY | **MUST** (any alg) | MAY |
| false | false | e.g. **PS256** | false | MAY | **MUST** (PS256) | MAY |
| false | false | undefined | **true** | **FORBIDDEN** | MAY (any alg) | **MUST** |

```
</details>

2020-05-11 08:23 UTC, vdzhuvinov commented
Is there a chance of having `require_request_objects` defined in the JAR spec?

2020-05-11 08:56 UTC, tlodderstedt commented
@panva your proposal looks good. Can you please modify the text?
@vdzhuvinov given the adapted meaning, this makes sense. I suggest to reach out to the JAR authors once we have the text settled.

2020-05-11 19:37 UTC, b---c requested changes
Based on the proposal and discussion around this at https://mailarchive.ietf.org/arch/msg/oauth/qvfhZIz08yRtuEbgA7Ryka0pPno/ and that #43 was to capture and track that, I would have expected to see `require_pushed_authorization_requests` metadata and associated behavior defined for both client and AS in the body of the document. The IANA stuff is for registration and has a description that will show up in the registry(s) to help understand it. But the IANA section doesn't define the parameters - that's done in the document.  

The inclusion of require_request_objects in this change was unexpected and I don't think it is appropriate here.

2020-05-11 19:47 UTC, b---c commented
also agree that PAR shouldn't be trying to apply special meaning to request_object_signing_alg

2020-05-11 19:55 UTC, b---c commented on main.md
> +An authorization server MAY decide to support pushed authorization requests as the only means for clients to pass authorization request data. In this case, the authorization server will refuse to pro
maybe unauthorized_client ?

2020-05-11 19:55 UTC, b---c commented on main.md
> +If the authorization server or the client's policy require use of request objects only at the pushed authorization endpoint, the authorization server will return a HTTP status code 400 along with the
unauthorized_client ?

2020-05-11 19:55 UTC, b---c commented on main.md
> +If the client uses dynamic client registration, setting the metadata parameter `request_object_signing_alg` MUST cause the authorization server to accept request objects for that particular client at
don't think this should be here

2020-05-11 20:19 UTC, tlodderstedt commented
@b---c 

> The inclusion of require_request_objects in this change was unexpected and I don't think it is appropriate here.

Why do you consider this inappropriate? Don't you think the AS should be able to decide to only accept request objects?

2020-05-11 20:53 UTC, b---c commented
> Why do you consider this inappropriate? 

Because there was some discussion and agreement around adding require_pushed_authorization_requests for client and server on the WG list for this document that is now a WG document. So that was the change I would have expected to see. And was even planning on making. But then that got put into a change with other stuff.

And require_request_objects was just thrown onto this PR. And that complicates reviewing and approving text for a change that was otherwise agreed to. 

Also, the name require_request_objects is general and independent of PAR so shouldn't have PAR specific meaning. And if it's not PAR specific but applicable to JAR in general, then it really shouldn't be defined in PAR but should be in JAR. Though I recognize that getting changes into JAR is complicated in its own right.  

> Don't you think the AS should be able to decide to only accept request objects?

An AS can decide that, of course. I'm not sure that a metadata parameter is needed for it though. And that should be a different conversation.

2020-05-12 06:23 UTC, tlodderstedt commented
I checked the respective threat again. 

https://mailarchive.ietf.org/arch/msg/oauth/1mzeKcb7I78AOGL8t-qNukkZyYc/

I had raised the question whether the AS should be able to require request object but the discussion then focussed on adoption of the OIDC mechanism to determine the client specific policy. When I wrote the PR, I remembered and added this metadata parameter since I thought it would be easier to discuss a concrete proposal. 

Sorry for any confusing this has caused. I will bring this topic to the list again.

2020-05-12 06:28 UTC, panva commented
Feel free to use the graphic i posted above. Imho the client alg property serves the same purpose and the new one is redundant.

2020-05-12 06:57 UTC, tlodderstedt commented
@panva Why does it serve the same purpose? In my opinion, it's a difference whether clients register with the intend to use request objects only or the AS deciding to only accept request objects.

2020-05-12 06:58 UTC, panva commented
> @panva Why does it serve the same purpose? In my opinion, it's a difference whether clients register with the intend to use request objects only or the AS deciding to only accept request objects.

fair enough.

2020-06-04 14:40 UTC, panva commented
On today's OIDC WG Call the presence of `request_object_signing_alg` as a signal to require the use of request objects was discussed and kind of disupted again with unclear way forward - see https://bitbucket.org/openid/connect/issues/1171/creating-a-way-to-mandate-request-object

2020-06-28 08:40 UTC, closed without merging