Add some guidance/options on the request URI structure
oauthstuff/draft-oauth-par pull request #48
Opened 2020-06-19 21:47 UTC by b---c

for #1 provide some more options/guidance on the request URI value including urn:ietf:params:oauth:request_uri:<reference-value> or a UUID as a URN per RFC4122

2020-06-22 03:46 UTC, davidgtonge commented
Looks good to me

2020-06-22 07:11 UTC, panva approved these changes

2020-06-24 10:11 UTC, tlodderstedt requested changes
looks good - proposed just a small change (may -> MAY)

2020-06-24 10:11 UTC, tlodderstedt commented on main.md
> +The format of the `request_uri` value is at the discretion of the authorization server but it MUST contain some part generated using a cryptographically strong pseudorandom algorithm such that it is
```suggestion
The format of the `request_uri` value is at the discretion of the authorization server but it MUST contain some part generated using a cryptographically strong pseudorandom algorithm such that it is computationally infeasible to predict or guess a valid value. The authorization server MAY construct the `request_uri` value using the form `urn:ietf:params:oauth:request_uri:<reference-value>` with `<reference-value>` as the random part of the URI that references the respective authorization request data. The string representation of a UUID as a URN per [@RFC4122] is also an option for authorization servers to construct `request_uri` values. 
```

2020-06-24 22:27 UTC, merged