Try and clarify the timing of request validation
oauthstuff/draft-oauth-par pull request #49
Opened 2020-06-19 22:25 UTC by b---c

for issue #38

2020-06-22 04:00 UTC, davidgtonge commented on main.md
> +3. The AS MUST validate the pushed request as it would an authorization request sent to the authorization endpoint, however the AS MAY omit validation steps that it is unable to perform when processi
I initially read the example as being for a step that the "AS may omit". Maybe we could break this into two parts:

> The AS MUST validate the pushed request as it would an authorization request sent to the authorization endpoint. For example, the authorization server checks whether the redirect URI matches one of the redirect URIs configured for the client and also checks whether the client is authorized for the `scope` for which it is requesting access. This validation allows the authorization server to refuse unauthorized or fraudulent requests early. 

> The AS MAY omit validation steps that it is unable to perform when processing the pushed request, however such checks MAST then be performed at the authorization endpoint.

2020-06-22 07:10 UTC, panva commented on main.md
> +3. The AS MUST validate the pushed request as it would an authorization request sent to the authorization endpoint, however the AS MAY omit validation steps that it is unable to perform when processi
I think this hits the nail right.

2020-06-22 15:18 UTC, b---c commented on main.md
> +3. The AS MUST validate the pushed request as it would an authorization request sent to the authorization endpoint, however the AS MAY omit validation steps that it is unable to perform when processi
Yeah, that's better. I'll adjust.

2020-06-22 15:29 UTC, b---c commented on main.md
> +3. The AS MUST validate the pushed request as it would an authorization request sent to the authorization endpoint, however the AS MAY omit validation steps that it is unable to perform when processi
261c17ad663a12abbd97600db6b6944e802370a3 makes that change

2020-06-24 10:14 UTC, tlodderstedt requested changes

2020-06-24 10:14 UTC, tlodderstedt commented on main.md
> +3. The AS MUST validate the pushed request as it would an authorization request sent to the authorization endpoint. For example, the authorization server checks whether the redirect URI matches one o
MAST -> MUST

2020-06-24 22:27 UTC, b---c commented on main.md
> +3. The AS MUST validate the pushed request as it would an authorization request sent to the authorization endpoint. For example, the authorization server checks whether the redirect URI matches one o
doh!

2020-06-24 22:39 UTC, merged